# docker create \
#         --name=reforger-server \
#         -p 2001:2001/udp \
#         -v path/to/configs:/reforger/Configs \
#         -v path/to/profiles:/home/profile \
#         -e SERVER_REGION="EU" \
#         -e SERVER_HOST_REGISTER_ADDRESS="public ip" \
#         -e GAME_NAME="My Docker Reforger Server" \
#         ghcr.io/acemod/arma-reforger:edge

version: '2'

services:
  reforger:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "2001:2001/udp"
    volumes:
      - path/to/configs:/reforger/Configs
      - path/to/profiles:/home/profile
    restart: always
    environment:
      - SERVER_REGION="US"
      - SERVER_HOST_REGISTER_ADDRESS="public ip"
      - GAME_NAME="ArgA Reforger Server"
    # labels:
    #   - traefik.http.routers.reforger-secure.rule=Host(`reforger.clanarga.com.ar`)
    #   - traefik.http.routers.reforger-secure.tls=true
    #   - traefik.http.routers.reforger-secure.tls.certresolver=lets-encrypt
    #   - "traefik.http.services.reforger.loadbalancer.server.port=2001"
  